### ISSUE TITLE
file.move silently overwrites existing files

### ISSUE THREAD

**Issue by DanielReedOcean** [rorynolan/filesstrings#4]
This package is great and much needed. One issue I have run into, though, is that `file.move` will silently overwrite existing files. I've included a reproducible example below.
```
# Create file
file.create("test.txt")

# Create directory
dir.create("MyDir")

# Move new file to new directory
file.move("test.txt", "MyDir")

# Create another file with the same name
file.create("test.txt")

# Move this file to the directory, silently overwriting previous file
file.move("test.txt", "MyDir")
```
Would it be possible to be given a warning or to be able to specify overwriting behaviour when calling the function (e.g.,  `file.move("test.txt", "MyDir", overwrite = FALSE)`)?

**Comment by rorynolan** [comment]
Hi @DanielReedOcean 
Thanks so much for your enthusiasm and great input. 
Thanks to your suggestion, `file.move()` now has an argument `overwrite` with default `FALSE` (7d8bfeb). This is something that should have always been there. I'll be submitting to CRAN in 3 weeks but you can install the dev version from github now. 
Thanks for your suggestion and if you have any more in future, I'd love to hear them.
Rory

**Comment by DanielReedOcean** [comment]
@rorynolan I've test driven the dev version and it works great. Thanks for the new functionality and the quick turnaround.
