### ISSUE TITLE
package ‘filestrings’ is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by denironyx** [rorynolan/filesstrings#7]
Hi maintainer, 

I was trying to explore the `filestrings` package to move folders within the R ecosystem. Unfortunately, it's sending me a warning message: 

> Warning in install.packages: package `filestrings` is not available (for R version 3.6.2).

Why am I getting this warning?

**Comment by rorynolan** [comment]
Hello!
Can you try `install.packages("filesstrings", type = "source")` please?
And please tell me what operating system you're using. 
Thanks, 
Rory

**Comment by denironyx** [comment]
Hey Rory, 

I tried running `install.packages("filestrings", type = "source")`. But, the warning persist. 

I am running a Windows Operating System.

**Comment by rorynolan** [comment]
I see the problem now. You're missing an s. You're typing `install.packages("filestrings")` instead of `install.packages("filesstrings")`. Easy mistake to make really.
Let me know if this sorts the problem for you.

**Comment by denironyx** [comment]
Awesome, It worked. 

I must confess that this is a great package.

**Comment by rorynolan** [comment]
Thank you!
For file manipulation, also check out the fs package (not mine).
