### ISSUE TITLE
filesstrings stringi dependency

### ISSUE THREAD

**Issue by oskar-november** [rorynolan/filesstrings#8]
Hi,
I updated my R packages recently. Since then when running filesstrings I get the error message below. I tried to update stringi to 1.5.3 but it always installs 1.4.6. I manually downloaded 1.5.3 and tried to install package from local without success. Is this something others have observed likewise?
 
Loading required package: stringr
Error: package or namespace load failed for ‘filesstrings’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘stringi’ 1.4.6 is already loaded, but >= 1.5 is required

**Comment by rorynolan** [comment]
Can you tell me what R version you're running?

**Comment by oskar-november** [comment]
Uh..I see what you mean. R 3.6. And R 4.0 came out last month. And I installed it and now everything is running fine! Thanks for your help!!
