### ISSUE TITLE
packages installation failed

### ISSUE THREAD

**Issue by nobie666** [rorynolan/filesstrings#9]
![image](https://user-images.githubusercontent.com/60246725/179358651-d5123527-4861-464a-a9a2-c1cd80035c36.png)
R3.6.3，I have got the problems above. Can you please help me solve this problem, thank you so much!

**Comment by rorynolan** [comment]
Dear @nobie666 
Can you please restart your R session and then try to install `filesstrings` from source with `install.packages("filesstrings", type = "source")` and tell me how it goes?
Thanks.
